name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller platformdirs

      - name: Build app
        run: |
          pyinstaller gui.py --name "rb2tk_gui" --windowed --onefile --icon=assets/rb2tk_ico.icns

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rb2tk_gui-macos
          path: dist/rb2tk_gui.app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Latest Build
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RB2TK_TOKEN }}

      - name: Upload macOS binary
        if: runner.os == 'macOS'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/rb2tk_gui.app
