name: Build Windows App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller platformdirs

      - name: Build app
        run: |
          pyinstaller gui.py --name "rb2tk_gui" --windowed --onefile --icon=assets/rb2tk_ico.ico

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rb2tk_gui-windows
          path: dist/rb2tk_gui.exe
